# Generated by Django 4.1.8 on 2023-04-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subject", "0002_subjecttimetable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderMailQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_on",
                    models.DateTimeField(verbose_name="sent reminder email on"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("start", "Start"), ("end", "end")],
                        max_length=6,
                        verbose_name="Reminder type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queue", "Queue"),
                            ("process", "Process"),
                            ("sent", "Sent"),
                            ("error", "Error"),
                        ],
                        default="queue",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "subject_timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subjecttimetable",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject_timetable", "type")},
            },
        ),
    ]
