# Generated by Django 4.1.8 on 2023-04-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subject", "0003_remindermailqueue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindermailqueue",
            name="subject_timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_timetable",
                to="subject.subjecttimetable",
            ),
        ),
    ]
